import { Tense, TenseCategory } from './types';

export const TENSE_CATEGORIES = Object.values(TenseCategory);

export const TENSES: Tense[] = [
  {
    id: 'present-simple',
    name: 'Present Simple',
    uzName: 'Oddiy hozirgi zamon',
    category: TenseCategory.PRESENT,
    formation: 'Subject + Verb (V1) (Add -s/es for he/she/it)',
    usage: ['Permanent actions', 'Habits', 'General facts'],
    uzUsage: ['Doimiy harakatlar', 'Odatlar', 'Umumiy faktlar'],
    examples: ['I play football.', 'She reads books.'],
    formula: {
      positive: 'Subject + V1',
      negative: 'Subject + do/does not + V1',
      question: 'Do/Does + subject + V1?',
    },
    games: [
      {
        id: 'ps-1',
        type: 'scramble',
        question: 'every day / She / books / reads',
        answer: 'She reads books every day',
        explanation: 'In Present Simple, we add -s to the verb for she/he/it.',
        uzExplanation: 'Oddiy hozirgi zamonda she/he/it uchun fe\'lga -s qo\'shiladi.'
      },
      {
        id: 'ps-error-1',
        type: 'error-hunt',
        question: 'She play tennis every Sunday.',
        answer: 'play',
        options: ['She', 'play', 'tennis'],
        explanation: 'In Present Simple, he/she/it takes -s/es.',
        uzExplanation: 'Oddiy hozirgi zamonda he/she/it uchun fe\'lga -s/es qo\'shiladi.'
      },
      {
        id: 'ps-err-4',
        type: 'error-hunt',
        question: 'Does they live in London?',
        answer: 'Does',
        options: ['Does', 'they', 'live'],
        explanation: 'Use "Do" with "they".',
        uzExplanation: '"they" bilan "Do" ishlatiladi.'
      },
      {
        id: 'ps-err-5',
        type: 'error-hunt',
        question: 'He don\'t care anymore.',
        answer: 'don\'t',
        options: ['He', 'don\'t', 'care'],
        explanation: 'Use "doesn\'t" for "he".',
        uzExplanation: '"he" uchun "doesn\'t" ishlatiladi.'
      },
      {
        id: 'ps-err-6',
        type: 'error-hunt',
        question: 'I like eats apples.',
        answer: 'eats',
        options: ['I', 'like', 'eats'],
        explanation: 'Do not add -s for "I".',
        uzExplanation: '"I" uchun fe\'lga -s qo\'shilmaydi.'
      },
      {
        id: 'ps-err-7',
        type: 'error-hunt',
        question: 'Do she know you?',
        answer: 'Do',
        options: ['Do', 'she', 'know'],
        explanation: 'Use "Does" for "she".',
        uzExplanation: '"she" uchun "Does" ishlatiladi.'
      },
      {
        id: 'ps-err-8',
        type: 'error-hunt',
        question: 'They doesn\'t work here.',
        answer: 'doesn\'t',
        options: ['They', 'doesn\'t', 'work'],
        explanation: 'Use "don\'t" for "they".',
        uzExplanation: '"they" uchun "don\'t" ishlatiladi.'
      },
      {
        id: 'ps-err-9',
        type: 'error-hunt',
        question: 'He always drink water.',
        answer: 'drink',
        options: ['He', 'always', 'drink'],
        explanation: 'Add -s for "he": drinks.',
        uzExplanation: '"he" uchun fe\'lga -s qo\'shiladi: drinks.'
      },
      {
        id: 'ps-err-10',
        type: 'error-hunt',
        question: 'Birds flies in the sky.',
        answer: 'flies',
        options: ['Birds', 'flies', 'sky'],
        explanation: 'Use plural verb form (fly) for "Birds".',
        uzExplanation: 'Ko\'plikdagi ot (Birds) uchun fe\'lning ashl shakli (fly) ishlatiladi.'
      }
    ]
  },
  {
    id: 'present-continuous',
    name: 'Present Continuous',
    uzName: 'Hozirgi davomli zamon',
    category: TenseCategory.PRESENT,
    formation: 'Subject + am/is/are + V-ing',
    usage: ['Actions happening now', 'Temporary situations'],
    uzUsage: ['Ayni damda sodir bo\'layotgan harakatlar', 'Vaqtinchalik holatlar'],
    examples: ['I am studying now.', 'They are playing.'],
    formula: {
      positive: 'Subject + am/is/are + V-ing',
      negative: 'Subject + am/is/are not + V-ing',
      question: 'Am/Is/Are + subject + V-ing?',
    },
    games: [
      {
        id: 'pc-1',
        type: 'scramble',
        question: 'studying / I / now / am',
        answer: 'I am studying now',
        explanation: 'Present Simple uses am/is/are + V-ing.',
        uzExplanation: 'Hozirgi davomli zamonda am/is/are + V-ing ishlatiladi.'
      },
      {
        id: 'pc-error-1',
        type: 'error-hunt',
        question: 'I am study English right now.',
        answer: 'study',
        options: ['am', 'study', 'English'],
        explanation: 'After "am/is/are", the verb must be in V-ing form.',
        uzExplanation: '"am/is/are" dan keyin fe\'l -ing shaklida bo\'lishi kerak.'
      },
      {
        id: 'pc-err-3',
        type: 'error-hunt',
        question: 'She is run to the bus.',
        answer: 'run',
        options: ['is', 'run', 'bus'],
        explanation: 'The verb should be "running".',
        uzExplanation: 'Fe\'l "running" bo\'lishi kerak.'
      },
      {
        id: 'pc-err-4',
        type: 'error-hunt',
        question: 'We am watching a movie.',
        answer: 'am',
        options: ['We', 'am', 'watching'],
        explanation: 'Use "are" with "we".',
        uzExplanation: '"we" bilan "are" ishlatiladi.'
      },
      {
        id: 'pc-err-5',
        type: 'error-hunt',
        question: 'They are play football.',
        answer: 'play',
        options: ['are', 'play', 'football'],
        explanation: 'Use "playing" after "are".',
        uzExplanation: '"are" dan keyin "playing" bo\'lishi kerak.'
      },
      {
        id: 'pc-err-6',
        type: 'error-hunt',
        question: 'Is you listening?',
        answer: 'Is',
        options: ['Is', 'you', 'listening'],
        explanation: 'Use "Are" with "you".',
        uzExplanation: '"you" uchun "Are" ishlatiladi.'
      },
      {
        id: 'pc-err-7',
        type: 'error-hunt',
        question: 'She are singing now.',
        answer: 'are',
        options: ['She', 'are', 'singing'],
        explanation: 'Use "is" for "she".',
        uzExplanation: '"she" uchun "is" ishlatiladi.'
      },
      {
        id: 'pc-err-8',
        type: 'error-hunt',
        question: 'I is working hard.',
        answer: 'is',
        options: ['I', 'is', 'working'],
        explanation: 'Use "am" for "I".',
        uzExplanation: '"I" uchun "am" ishlatiladi.'
      },
      {
        id: 'pc-err-9',
        type: 'error-hunt',
        question: 'We are watch TV.',
        answer: 'watch',
        options: ['are', 'watch', 'TV'],
        explanation: 'Use "watching" after "are".',
        uzExplanation: '"are" dan keyin "watching" bo\'lishi kerak.'
      }
    ]
  },
  {
    id: 'present-perfect',
    name: 'Present Perfect',
    uzName: 'Hozirgi tugallangan zamon',
    category: TenseCategory.PRESENT,
    formation: 'Subject + have/has + V3',
    usage: ['Recently finished actions', 'Actions where result is important', 'Life experience'],
    uzUsage: ['Yaqinda tugallangan harakatlar', 'Natijasi muhim bo\'lgan harakatlar', 'Hayotiy tajriba'],
    examples: ['I have finished my homework.', 'She has gone to school.'],
    formula: {
      positive: 'Subject + have/has + V3',
      negative: 'Subject + have/has not + V3',
      question: 'Have/Has + subject + V3?',
    },
    games: [
      {
        id: 'pp-1',
        type: 'scramble',
        question: 'homework / finished / I / my / have',
        answer: 'I have finished my homework',
        explanation: 'Present Perfect uses have/has + the past participle (V3).',
        uzExplanation: 'Hozirgi tugallangan zamonda have/has + fe\'lning 3-shakli (V3) ishlatiladi.'
      },
      {
        id: 'pp-err-1',
        type: 'error-hunt',
        question: 'She have cleaned the room.',
        answer: 'have',
        options: ['She', 'have', 'cleaned'],
        explanation: 'She/he/it takes "has" in Present Perfect.',
        uzExplanation: 'She/he/it uchun Present Perfect\'da "has" ishlatiladi.'
      },
      {
        id: 'pp-err-3',
        type: 'error-hunt',
        question: 'I has finished my meal.',
        answer: 'has',
        options: ['I', 'has', 'finished'],
        explanation: 'Use "have" for "I".',
        uzExplanation: '"I" uchun "have" ishlatiladi.'
      },
      {
        id: 'pp-err-4',
        type: 'error-hunt',
        question: 'They have ate everything.',
        answer: 'ate',
        options: ['have', 'ate', 'everything'],
        explanation: 'Use V3 (eaten) after have/has.',
        uzExplanation: 'have/has dan keyin V3 (eaten) ishlatiladi.'
      },
      {
        id: 'pp-err-5',
        type: 'error-hunt',
        question: 'Has you seen him?',
        answer: 'Has',
        options: ['Has', 'you', 'seen'],
        explanation: 'Use "Have" for "you".',
        uzExplanation: '"you" uchun "Have" ishlatiladi.'
      },
      {
        id: 'pp-err-6',
        type: 'error-hunt',
        question: 'I have went there.',
        answer: 'went',
        options: ['have', 'went', 'there'],
        explanation: 'Use V3 (gone) after have.',
        uzExplanation: 'have dan keyin V3 (gone) ishlatiladi.'
      },
      {
        id: 'pp-err-7',
        type: 'error-hunt',
        question: 'She has saw the movie.',
        answer: 'saw',
        options: ['has', 'saw', 'movie'],
        explanation: 'Use V3 (seen) after has.',
        uzExplanation: 'has dan keyin V3 (seen) ishlatiladi.'
      },
      {
        id: 'pp-err-8',
        type: 'error-hunt',
        question: 'We has arrived.',
        answer: 'has',
        options: ['We', 'has', 'arrived'],
        explanation: 'Use "have" for "we".',
        uzExplanation: '"we" uchun "have" ishlatiladi.'
      }
    ]
  },
  {
    id: 'present-perfect-continuous',
    name: 'Present Perfect Continuous',
    uzName: 'Hozirgi tugallangan davomli zamon',
    category: TenseCategory.PRESENT,
    formation: 'Subject + have/has been + V-ing',
    usage: ['Actions that started in the past and continue to the present', 'How long an action has been happening'],
    uzUsage: ['O\'tmishda boshlanib, hozirgacha davom etayotgan harakatlar', 'Harakat qancha davom etganligi'],
    examples: ['I have been studying for 2 hours.', 'He has been working since morning.'],
    games: [
      {
        id: 'ppc-1',
        type: 'scramble',
        question: 'for 2 hours / studying / been / I / have',
        answer: 'I have been studying for 2 hours',
        uzExplanation: 'Bu zamon harakatning qancha vaqtdan beri davom etayotganini ko\'rsatadi.'
      }
    ]
  },
  {
    id: 'past-simple',
    name: 'Past Simple',
    uzName: 'Oddiy o\'tgan zamon',
    category: TenseCategory.PAST,
    formation: 'Subject + V2 (ed/irregular)',
    usage: ['Completed actions in the past'],
    uzUsage: ['O\'tmishda tugallangan harakatlar'],
    examples: ['I visited Samarkand.', 'She cooked dinner.'],
    formula: {
      positive: 'Subject + V2',
      negative: 'Subject + did not + V1',
      question: 'Did + subject + V1?',
    },
    games: [
      {
        id: 'ps-simple-1',
        type: 'scramble',
        question: 'yesterday / soccer / They / played',
        answer: 'They played soccer yesterday',
        uzExplanation: 'O\'tgan zamonda fe\'lga -ed qo\'shiladi yoki noto\'g\'ri fe\'l shakli (V2) ishlatiladi.'
      },
      {
        id: 'ps-err-2',
        type: 'error-hunt',
        question: 'I goed to the cinema last night.',
        answer: 'goed',
        options: ['goed', 'cinema', 'night'],
        explanation: '"Go" is an irregular verb. Past simple is "went".',
        uzExplanation: '"Go" noto\'g\'ri fe\'l. O\'tgan zamon shakli "went" bo\'ladi.'
      },
      {
        id: 'ps-err-6',
        type: 'error-hunt',
        question: 'They didn\'t played yesterday.',
        answer: 'played',
        options: ['didn\'t', 'played', 'yesterday'],
        explanation: 'After "didn\'t", use the base form of the verb.',
        uzExplanation: '"didn\'t" dan keyin fe\'lning ashl shakli ishlatiladi.'
      },
      {
        id: 'ps-err-7',
        type: 'error-hunt',
        question: 'Was you at home?',
        answer: 'Was',
        options: ['Was', 'you', 'home'],
        explanation: 'Use "Were" with "you".',
        uzExplanation: '"you" uchun "Were" ishlatiladi.'
      },
      {
        id: 'ps-err-8',
        type: 'error-hunt',
        question: 'She didn\'t cooked dinner.',
        answer: 'cooked',
        options: ['didn\'t', 'cooked', 'dinner'],
        explanation: 'Use base form (cook) after "didn\'t".',
        uzExplanation: '"didn\'t" dan keyin fe\'lning ashl shakli (cook) ishlatiladi.'
      },
      {
        id: 'past-err-10',
        type: 'error-hunt',
        question: 'He didn\'t ate his bread.',
        answer: 'ate',
        options: ['didn\'t', 'ate', 'bread'],
        explanation: 'Use base form (eat) after "didn\'t".',
        uzExplanation: '"didn\'t" dan keyin fe\'lning ashl shakli (eat) ishlatiladi.'
      },
      {
        id: 'past-err-11',
        type: 'error-hunt',
        question: 'I was went to school.',
        answer: 'was went',
        options: ['I', 'was went', 'school'],
        explanation: 'Do not use "was" with a past verb. Just "went".',
        uzExplanation: 'Past Simple\'da "was" biron bir fe\'l bilan birga kelmasligi kerak. Shunchaki "went" bo\'ladi.'
      }
    ]
  },
  {
    id: 'past-continuous',
    name: 'Past Continuous',
    uzName: 'O\'tgan davomli zamon',
    category: TenseCategory.PAST,
    formation: 'Subject + was/were + V-ing',
    usage: ['Actions in progress at a specific time in the past'],
    uzUsage: ['O\'tmishning ma\'lum bir vaqtida davom etayotgan harakatlar'],
    examples: ['I was reading at 8 PM.', 'They were playing football.'],
    games: [
      {
        id: 'pa-c-1',
        type: 'scramble',
        question: 'was / I / reading / 8 PM / at',
        answer: 'I was reading at 8 PM',
        uzExplanation: 'O\'tgan davomli zamonda was/were + V-ing ishlatiladi.'
      },
      {
        id: 'pc-err-2',
        type: 'error-hunt',
        question: 'They was watching TV.',
        answer: 'was',
        options: ['They', 'was', 'watching'],
        explanation: '"They" takes "were" in Past Continuous.',
        uzExplanation: '"They" uchun o\'tgan davomli zamonda "were" ishlatiladi.'
      }
    ]
  },
  {
    id: 'past-perfect',
    name: 'Past Perfect',
    uzName: 'O\'tgan tugallangan zamon',
    category: TenseCategory.PAST,
    formation: 'Subject + had + V3',
    usage: ['Actions finished before another past action'],
    uzUsage: ['O\'tmishdagi boshqa bir harakatdan oldin tugallangan harakatlar'],
    examples: ['I had finished before he came.', 'She had left already.'],
    games: [
      {
        id: 'pa-p-1',
        type: 'scramble',
        question: 'before / he / had / arrived / I / left',
        answer: 'I had left before he arrived',
        uzExplanation: 'Boshqa o\'tgan zamon harakatidan oldin sodir bo\'lgan harakat uchun had + V3 ishlatiladi.'
      }
    ]
  },
  {
    id: 'past-perfect-continuous',
    name: 'Past Perfect Continuous',
    uzName: 'O\'tgan tugallangan davomli zamon',
    category: TenseCategory.PAST,
    formation: 'Subject + had been + V-ing',
    usage: ['Continuous action in the past before another past point'],
    uzUsage: ['O\'tmishdagi ma\'lum bir nuqtadan oldin davom etgan harakatlar'],
    examples: ['I had been studying for 3 hours.', 'They had been waiting long.'],
    games: [
       {
        id: 'pa-pc-1',
        type: 'scramble',
        question: 'for 3 hours / studying / had / been / I',
        answer: 'I had been studying for 3 hours',
        uzExplanation: 'Harakat o\'tmishdagi boshqa voqeadan oldin qancha davom etganini ko\'rsatadi.'
      }
    ]
  },
  {
    id: 'future-simple',
    name: 'Future Simple',
    uzName: 'Oddiy kelasi zamon',
    category: TenseCategory.FUTURE,
    formation: 'Subject + will + V1',
    usage: ['Simple future actions', 'Predictions', 'Sudden decisions'],
    uzUsage: ['Oddiy kelasi zamon harakatlari', 'Bashoratlar', 'To\'satdan qabul qilingan qarorlar'],
    examples: ['I will help you.', 'She will come tomorrow.'],
    games: [
      {
        id: 'f-s-1',
        type: 'scramble',
        question: 'help / will / I / you',
        answer: 'I will help you',
        uzExplanation: 'Kelasi zamonda will + V1 ishlatiladi.'
      },
      {
        id: 'fs-err-1',
        type: 'error-hunt',
        question: 'I will to help you.',
        answer: 'to',
        options: ['will', 'to', 'help'],
        explanation: 'Do not use "to" after "will".',
        uzExplanation: '"will" dan keyin "to" ishlatilmaydi.'
      },
      {
        id: 'fs-err-2',
        type: 'error-hunt',
        question: 'She will comes tonight.',
        answer: 'comes',
        options: ['will', 'comes', 'tonight'],
        explanation: 'After "will", use the base form (come).',
        uzExplanation: '"will" dan keyin fe\'lning ashl shakli (come) ishlatiladi.'
      },
      {
        id: 'fs-err-3',
        type: 'error-hunt',
        question: 'We will going to the party.',
        answer: 'going',
        options: ['will', 'going', 'party'],
        explanation: 'Use base form (go) after "will".',
        uzExplanation: '"will" dan keyin fe\'lning ashl shakli (go) ishlatiladi.'
      },
      {
        id: 'fs-err-4',
        type: 'error-hunt',
        question: 'I will be see you.',
        answer: 'be see',
        options: ['I', 'will', 'be see'],
        explanation: 'Use "will see" or "will be seeing".',
        uzExplanation: '"will see" yoki "will be seeing" bo\'lishi kerak.'
      },
      {
        id: 'fs-err-5',
        type: 'error-hunt',
        question: 'They will don\'t come.',
        answer: 'will don\'t',
        options: ['will don\'t', 'come', 'party'],
        explanation: 'Use "won\'t" for future negative.',
        uzExplanation: 'Kelasi zamon inkor shakli uchun "won\'t" ishlatiladi.'
      }
    ]
  },
  {
    id: 'future-continuous',
    name: 'Future Continuous',
    uzName: 'Kelasi davomli zamon',
    category: TenseCategory.FUTURE,
    formation: 'Subject + will be + V-ing',
    usage: ['Actions that will be in progress at a time in the future'],
    uzUsage: ['Kelajakning ma\'lum bir vaqtida davom etayotgan bo\'ladigan harakatlar'],
    examples: ['I will be studying at 9 PM.', 'They will be traveling tomorrow.'],
    games: [
      {
        id: 'f-c-1',
        type: 'scramble',
        question: 'be / 9 PM / will / I / at / studying',
        answer: 'I will be studying at 9 PM',
        uzExplanation: 'Kelasi davomli zamon uchun will be + V-ing qo\'llaniladi.'
      }
    ]
  },
  {
    id: 'future-perfect',
    name: 'Future Perfect',
    uzName: 'Kelasi tugallangan zamon',
    category: TenseCategory.FUTURE,
    formation: 'Subject + will have + V3',
    usage: ['Actions that will be completed by a specific future time'],
    uzUsage: ['Kelajakdagi ma\'lum bir vaqtgacha tugallanadigan harakatlar'],
    examples: ['I will have finished by 5 o’clock.', 'She will have arrived soon.'],
    games: [
      {
        id: 'f-p-1',
        type: 'scramble',
        question: "finished / o'clock / I / will / by / 5 / have",
        answer: "I will have finished by 5 o'clock",
        explanation: 'Future Perfect uses will have + V3.',
        uzExplanation: 'Kelasi tugallangan zamon will have + V3 orqali yasaladi.'
      }
    ]
  },
  {
    id: 'future-perfect-continuous',
    name: 'Future Perfect Continuous',
    uzName: 'Kelasi tugallangan davomli zamon',
    category: TenseCategory.FUTURE,
    formation: 'Subject + will have been + V-ing',
    usage: ['How long an action will have been happening until a future point'],
    uzUsage: ['Kelajakdagi nuqtada harakat qancha vaqtdan beri davom etayotgan bo\'lishi'],
    examples: ['I will have been working for 5 years.', 'They will have been studying for hours.'],
    games: [
      {
        id: 'f-pc-1',
        type: 'scramble',
        question: 'for / have / 5 years / been / working / will / I',
        answer: 'I will have been working for 5 years',
        uzExplanation: 'Kelajakdagi vaqt nuqtasida harakat davomiyligini ko\'rsatadi.'
      }
    ]
  },
  {
    id: 'past-future-simple',
    name: 'Past Future Simple',
    uzName: 'O\'tgan zamondagi kelasi oddiy zamon',
    category: TenseCategory.PAST_FUTURE,
    formation: 'Subject + would + V1',
    usage: ['Future in the past', 'Conditional sentences'],
    uzUsage: ['O\'tmishdagi kelajak (hikoya qilinganda)', 'Shartli gaplar'],
    examples: ['He said he would come.', 'I knew she would help.'],
    games: [
      {
        id: 'pf-s-1',
        type: 'scramble',
        question: 'he / come / said / would / He',
        answer: 'He said he would come',
        uzExplanation: 'Hikoya shaklida will o\'rniga would ishlatiladi.'
      }
    ]
  },
  {
    id: 'past-future-continuous',
    name: 'Past Future Continuous',
    uzName: 'O\'tgan zamondagi kelasi davomli zamon',
    category: TenseCategory.PAST_FUTURE,
    formation: 'Subject + would be + V-ing',
    usage: ['Actions that would have been in progress at a time in the past-future context'],
    uzUsage: ['O\'tmishdagi kelajakda davom etayotgan bo\'ladigan harakatlar'],
    examples: ['He said he would be working.', 'I thought they would be waiting.'],
    games: [
      {
        id: 'pf-c-1',
        type: 'scramble',
        question: 'working / said / would / He / be / he',
        answer: 'He said he would be working',
        uzExplanation: 'Would be + V-ing o\'tmishdagi kelajak davomli harakatini bildiradi.'
      }
    ]
  },
  {
    id: 'past-future-perfect',
    name: 'Past Future Perfect',
    uzName: 'O\'tgan zamondagi kelasi tugallangan zamon',
    category: TenseCategory.PAST_FUTURE,
    formation: 'Subject + would have + V3',
    usage: ['Actions that would have been completed in a past-future context'],
    uzUsage: ['O\'tmishdagi kelajakda tugallangan bo\'ladigan harakatlar'],
    examples: ['She said she would have finished.', 'I thought he would have arrived.'],
    games: [
      {
        id: 'pf-p-1',
        type: 'scramble',
        question: 'would / said / She / have / finished / she',
        answer: 'She said she would have finished',
        uzExplanation: 'Would have + V3 tugallangan o\'tmish-kelajak harakati.'
      }
    ]
  },
  {
    id: 'past-future-perfect-continuous',
    name: 'Past Future Perfect Continuous',
    uzName: 'O\'tgan zamondagi kelasi tugallangan davomli zamon',
    category: TenseCategory.PAST_FUTURE,
    formation: 'Subject + would have been + V-ing',
    usage: ['How long an action would have been happening in a past-future context'],
    uzUsage: ['O\'tmishdagi kelajakda harakat qancha davom etgan bo\'lishi'],
    examples: ['He said he would have been working for 2 hours.', 'I thought they would have been studying.'],
    games: [
      {
        id: 'pf-pc-1',
        type: 'scramble',
        question: 'working / been / for / have / he / 2 hours / would / said / He',
        answer: 'He said he would have been working for 2 hours',
        uzExplanation: 'O\'tmishdagi kelajakda harakat davomiyligini ifodalaydi.'
      }
    ]
  },
  {
    id: 'adjectives-order',
    name: 'Order of Adjectives',
    uzName: 'Sifatlar tartibi',
    category: TenseCategory.GRAMMAR,
    formation: 'Opinion + Size + Age + Shape + Color + Origin + Material + Purpose',
    usage: ['The correct sequence when using multiple adjectives before a noun'],
    uzUsage: ['Otlar oldidan bir nechta sifatlar kelganda ularning to\'g\'ri tartibi'],
    examples: ['A beautiful big old brown table.', 'An amazing small new red French car.'],
    games: [
      {
        id: 'adj-order-1',
        type: 'choice',
        question: 'Choose the correct order: (small / new / red)',
        answer: 'small new red',
        options: ['red small new', 'small new red', 'new small red'],
        uzExplanation: 'Tartib: Size (small), Age (new), Color (red).'
      },
      {
        id: 'adj-order-2',
        type: 'choice',
        question: 'Choose the correct order: (Italian / delicious / old)',
        answer: 'delicious old Italian',
        options: ['Italian delicious old', 'delicious old Italian', 'old Italian delicious'],
        uzExplanation: 'Tartib: Opinion (delicious), Age (old), Origin (Italian).'
      },
      {
        id: 'adj-order-3',
        type: 'error-hunt',
        question: 'I have a red big car.',
        answer: 'red big',
        options: ['red big', 'have', 'car'],
        explanation: 'Size comes before Color. It should be "big red".',
        uzExplanation: 'Size (katta) Color (rang)dan oldin keladi. "big red" bo\'lishi kerak.'
      }
    ]
  }
];

export const DICTIONARY_DATA = [
  { en: 'I', uz: 'men' },
  { en: 'you', uz: 'sen / siz' },
  { en: 'he', uz: 'u (erkak)' },
  { en: 'she', uz: 'u (ayol)' },
  { en: 'it', uz: 'u (narsa)' },
  { en: 'we', uz: 'biz' },
  { en: 'they', uz: 'ular' },
  { en: 'this', uz: 'bu' },
  { en: 'that', uz: 'ana u' },
  { en: 'here', uz: 'bu yerda' },
  { en: 'there', uz: 'u yerda' },
  { en: 'what', uz: 'nima' },
  { en: 'who', uz: 'kim' },
  { en: 'when', uz: 'qachon' },
  { en: 'where', uz: 'qayerda' },
  { en: 'why', uz: 'nega' },
  { en: 'how', uz: 'qanday' },
  { en: 'yes', uz: 'ha' },
  { en: 'no', uz: 'yo‘q' },
  { en: 'not', uz: 'emas' },
  { en: 'all', uz: 'hamma' },
  { en: 'many', uz: 'ko‘p' },
  { en: 'some', uz: 'ba’zi' },
  { en: 'one', uz: 'bir' },
  { en: 'two', uz: 'ikki' },
  { en: 'three', uz: 'uch' },
  { en: 'big', uz: 'katta' },
  { en: 'small', uz: 'kichik' },
  { en: 'good', uz: 'yaxshi' },
  { en: 'bad', uz: 'yomon' },
  { en: 'new', uz: 'yangi' },
  { en: 'old', uz: 'eski' },
  { en: 'young', uz: 'yosh' },
  { en: 'man', uz: 'erkak' },
  { en: 'woman', uz: 'ayol' },
  { en: 'child', uz: 'bola' },
  { en: 'friend', uz: 'do‘st' },
  { en: 'family', uz: 'oila' },
  { en: 'house', uz: 'uy' },
  { en: 'room', uz: 'xona' },
  { en: 'school', uz: 'maktab' },
  { en: 'teacher', uz: 'o‘qituvchi' },
  { en: 'student', uz: 'talaba / o‘quvchi' },
  { en: 'book', uz: 'kitob' },
  { en: 'pen', uz: 'ruchka' },
  { en: 'table', uz: 'stol' },
  { en: 'chair', uz: 'stul' },
  { en: 'food', uz: 'ovqat' },
  { en: 'water', uz: 'suv' },
  { en: 'bread', uz: 'non' },
  { en: 'tea', uz: 'choy' },
  { en: 'milk', uz: 'sut' },
  { en: 'apple', uz: 'olma' },
  { en: 'car', uz: 'mashina' },
  { en: 'bus', uz: 'avtobus' },
  { en: 'road', uz: 'yo‘l' },
  { en: 'city', uz: 'shahar' },
  { en: 'country', uz: 'davlat' },
  { en: 'work', uz: 'ish' },
  { en: 'job', uz: 'kasb' },
  { en: 'money', uz: 'pul' },
  { en: 'time', uz: 'vaqt' },
  { en: 'day', uz: 'kun' },
  { en: 'night', uz: 'tun' },
  { en: 'morning', uz: 'ertalab' },
  { en: 'evening', uz: 'kechqurun' },
  { en: 'today', uz: 'bugun' },
  { en: 'tomorrow', uz: 'ertaga' },
  { en: 'yesterday', uz: 'kecha' },
  { en: 'love', uz: 'sevmoq' },
  { en: 'like', uz: 'yoqtirmoq' },
  { en: 'want', uz: 'xohlamoq' },
  { en: 'need', uz: 'kerak bo‘lmoq' },
  { en: 'go', uz: 'bormoq' },
  { en: 'come', uz: 'kelmoq' },
  { en: 'see', uz: 'ko‘rmoq' },
  { en: 'hear', uz: 'eshitmoq' },
  { en: 'speak', uz: 'gapirmoq' },
  { en: 'read', uz: 'o‘qimoq' },
  { en: 'write', uz: 'yozmoq' },
  { en: 'eat', uz: 'yemoq' },
  { en: 'drink', uz: 'ichmoq' },
  { en: 'sleep', uz: 'uxlamoq' },
  { en: 'live', uz: 'yashamoq' },
  { en: 'open', uz: 'ochmoq' },
  { en: 'close', uz: 'yopmoq' },
  { en: 'start', uz: 'boshlamoq' },
  { en: 'finish', uz: 'tugatmoq' },
  { en: 'help', uz: 'yordam' },
  { en: 'ask', uz: 'so‘ramoq' },
  { en: 'answer', uz: 'javob' },
  { en: 'understand', uz: 'tushunmoq' },
  { en: 'remember', uz: 'eslamoq' },
  { en: 'forget', uz: 'unutmoq' },
  { en: 'happy', uz: 'xursand' },
  { en: 'sad', uz: 'xafa' },
  { en: 'beautiful', uz: 'chiroyli' },
  { en: 'strong', uz: 'kuchli' },
  { en: 'fast', uz: 'tez' },
  { en: 'slow', uz: 'sekin' },
  { en: 'computer', uz: 'kompyuter' },
  { en: 'phone', uz: 'telefon' },
  { en: 'internet', uz: 'internet' },
  { en: 'window', uz: 'deraza' },
  { en: 'door', uz: 'eshik' },
  { en: 'key', uz: 'kalit' },
  { en: 'bag', uz: 'sumka' },
  { en: 'clothes', uz: 'kiyimlar' },
  { en: 'shirt', uz: 'ko‘ylak' },
  { en: 'shoes', uz: 'oyoq kiyim' },
  { en: 'market', uz: 'bozor' },
  { en: 'shop', uz: 'do‘kon' },
  { en: 'hospital', uz: 'kasalxona' },
  { en: 'doctor', uz: 'shifokor' },
  { en: 'nurse', uz: 'hamshira' },
  { en: 'police', uz: 'politsiya' },
  { en: 'airport', uz: 'aeroport' },
  { en: 'station', uz: 'vokzal' },
  { en: 'train', uz: 'poyezd' },
  { en: 'airplane', uz: 'samolyot' },
  { en: 'ticket', uz: 'chipta' },
  { en: 'hotel', uz: 'mehmonxona' },
  { en: 'restaurant', uz: 'restoran' },
  { en: 'breakfast', uz: 'nonushta' },
  { en: 'lunch', uz: 'tushlik' },
  { en: 'dinner', uz: 'kechki ovqat' },
  { en: 'meat', uz: 'go‘sht' },
  { en: 'rice', uz: 'guruch' },
  { en: 'soup', uz: 'sho‘rva' },
  { en: 'salt', uz: 'tuz' },
  { en: 'sugar', uz: 'shakar' },
  { en: 'coffee', uz: 'qahva' },
  { en: 'juice', uz: 'sharbat' },
  { en: 'fruit', uz: 'meva' },
  { en: 'vegetable', uz: 'sabzavot' },
  { en: 'banana', uz: 'banan' },
  { en: 'orange', uz: 'apelsin' },
  { en: 'red', uz: 'qizil' },
  { en: 'blue', uz: 'ko‘k' },
  { en: 'green', uz: 'yashil' },
  { en: 'black', uz: 'qora' },
  { en: 'white', uz: 'oq' },
  { en: 'yellow', uz: 'sariq' },
  { en: 'hot', uz: 'issiq' },
  { en: 'cold', uz: 'sovuq' },
  { en: 'warm', uz: 'iliq' },
  { en: 'easy', uz: 'oson' },
  { en: 'difficult', uz: 'qiyin' },
  { en: 'important', uz: 'muhim' },
  { en: 'interesting', uz: 'qiziq' },
  { en: 'expensive', uz: 'qimmat' },
  { en: 'cheap', uz: 'arzon' },
  { en: 'rich', uz: 'boy' },
  { en: 'poor', uz: 'kambag‘al' },
  { en: 'busy', uz: 'band' },
  { en: 'free', uz: 'bo‘sh' },
  { en: 'early', uz: 'erta' },
  { en: 'late', uz: 'kech' },
  { en: 'always', uz: 'har doim' },
  { en: 'never', uz: 'hech qachon' },
  { en: 'sometimes', uz: 'ba’zan' },
  { en: 'often', uz: 'tez-tez' },
  { en: 'now', uz: 'hozir' },
  { en: 'soon', uz: 'tez orada' },
  { en: 'again', uz: 'yana' },
  { en: 'before', uz: 'oldin' },
  { en: 'after', uz: 'keyin' },
  { en: 'inside', uz: 'ichida' },
  { en: 'outside', uz: 'tashqarida' },
  { en: 'above', uz: 'tepada' },
  { en: 'below', uz: 'pastda' },
  { en: 'near', uz: 'yaqin' },
  { en: 'far', uz: 'uzoq' },
  { en: 'left', uz: 'chap' },
  { en: 'right', uz: 'o‘ng' },
  { en: 'mother', uz: 'ona' },
  { en: 'father', uz: 'ota' },
  { en: 'brother', uz: 'aka / uka' },
  { en: 'sister', uz: 'opa / singil' },
  { en: 'son', uz: 'o‘g‘il' },
  { en: 'daughter', uz: 'qiz' },
  { en: 'uncle', uz: 'amaki / tog‘a' },
  { en: 'aunt', uz: 'amma / xola' },
  { en: 'cousin', uz: 'amakivachcha' },
  { en: 'baby', uz: 'chaqaloq' },
  { en: 'name', uz: 'ism' },
  { en: 'age', uz: 'yosh' },
  { en: 'birthday', uz: 'tug‘ilgan kun' },
  { en: 'photo', uz: 'rasm' },
  { en: 'music', uz: 'musiqa' },
  { en: 'movie', uz: 'kino' },
  { en: 'game', uz: 'o‘yin' },
  { en: 'sport', uz: 'sport' },
  { en: 'football', uz: 'futbol' },
  { en: 'tennis', uz: 'tennis' },
  { en: 'run', uz: 'yugurmoq' },
  { en: 'walk', uz: 'yurmoq' },
  { en: 'swim', uz: 'suzmoq' },
  { en: 'dance', uz: 'raqs tushmoq' },
  { en: 'sing', uz: 'kuylamoq' },
  { en: 'smile', uz: 'tabassum' },
  { en: 'laugh', uz: 'kulmoq' },
  { en: 'cry', uz: 'yig‘lamoq' },
  { en: 'think', uz: 'o‘ylamoq' },
  { en: 'know', uz: 'bilmoq' },
  { en: 'learn', uz: 'o‘rganmoq' },
  { en: 'teach', uz: 'o‘qitmoq' },
  { en: 'study', uz: 'o‘qimoq' },
  { en: 'use', uz: 'foydalanmoq' },
  { en: 'pay', uz: 'to‘lamoq' },
  { en: 'buy', uz: 'sotib olmoq' },
  { en: 'sell', uz: 'sotmoq' },
  { en: 'wait', uz: 'kutmoq' },
  { en: 'send', uz: 'yubormoq' },
  { en: 'receive', uz: 'qabul qilmoq' },
  { en: 'call', uz: 'qo‘ng‘iroq qilmoq' },
  { en: 'meet', uz: 'uchrashmoq' },
  { en: 'travel', uz: 'sayohat qilmoq' },
  { en: 'arrive', uz: 'yetib kelmoq' },
  { en: 'leave', uz: 'ketmoq' },
  { en: 'win', uz: 'yutmoq' },
  { en: 'lose', uz: 'yutqazmoq' },
  { en: 'build', uz: 'qurmoq' },
  { en: 'clean', uz: 'tozalamoq' },
  { en: 'wash', uz: 'yuvmoq' },
  { en: 'cook', uz: 'ovqat pishirmoq' },
  { en: 'cut', uz: 'kesmoq' },
  { en: 'break', uz: 'sindirmoq' },
  { en: 'drive', uz: 'haydamoq' },
  { en: 'sit', uz: 'o‘tirmoq' },
  { en: 'stand', uz: 'turmoq' },
  { en: 'open_adj', uz: 'ochiq' },
  { en: 'closed', uz: 'yopiq' },
  { en: 'strong_adj', uz: 'baquvvat' },
  { en: 'weak', uz: 'kuchsiz' },
  { en: 'hungry', uz: 'och' },
  { en: 'thirsty', uz: 'chanqagan' },
  { en: 'tired', uz: 'charchagan' },
  { en: 'sick', uz: 'kasal' },
  { en: 'healthy', uz: 'sog‘lom' },
  { en: 'dangerous', uz: 'xavfli' },
  { en: 'safe', uz: 'xavfsiz' },
  { en: 'true', uz: 'rost' },
  { en: 'false', uz: 'yolg‘on' },
  { en: 'same', uz: 'bir xil' },
  { en: 'different', uz: 'boshqacha' },
  { en: 'full', uz: 'to‘la' },
  { en: 'empty', uz: 'bo‘sh' },
  { en: 'dark', uz: 'qorong‘i' },
  { en: 'light', uz: 'yorug‘' },
  { en: 'weather', uz: 'ob-havo' },
  { en: 'rain', uz: 'yomg\'ir' },
  { en: 'snow', uz: 'qor' },
  { en: 'wind', uz: 'shamol' },
  { en: 'sun', uz: 'quyosh' },
  { en: 'moon', uz: 'oy' },
  { en: 'star', uz: 'yulduz' },
  { en: 'sky', uz: 'osmon' },
  { en: 'sea', uz: 'dengiz' },
  { en: 'achieve', uz: 'erishmoq' },
  { en: 'improve', uz: 'yaxshilamoq' },
  { en: 'increase', uz: 'oshirmoq' },
  { en: 'decrease', uz: 'kamaytirmoq' },
  { en: 'develop', uz: 'rivojlantirmoq' },
  { en: 'education', uz: 'ta’lim' },
  { en: 'environment', uz: 'atrof-muhit' },
  { en: 'technology', uz: 'texnologiya' },
  { en: 'government', uz: 'hukumat' },
  { en: 'society', uz: 'jamiyat' },
  { en: 'opportunity', uz: 'imkoniyat' },
  { en: 'advantage', uz: 'afzallik' },
  { en: 'disadvantage', uz: 'kamchilik' },
  { en: 'experience', uz: 'tajriba' },
  { en: 'knowledge', uz: 'bilim' },
  { en: 'research', uz: 'tadqiqot' },
  { en: 'solution', uz: 'yechim' },
  { en: 'problem', uz: 'muammo' },
  { en: 'success', uz: 'muvaffaqiyat' },
  { en: 'failure', uz: 'muvaffaqiyatsizlik' },
  { en: 'career', uz: 'karyera' },
  { en: 'skill', uz: 'ko‘nikma' },
  { en: 'communication', uz: 'muloqot' },
  { en: 'culture', uz: 'madaniyat' },
  { en: 'tradition', uz: 'an’ana' },
  { en: 'population', uz: 'aholi' },
  { en: 'economy', uz: 'iqtisodiyot' },
  { en: 'employment', uz: 'bandlik' },
  { en: 'unemployment', uz: 'ishsizlik' },
  { en: 'global', uz: 'global' },
  { en: 'local', uz: 'mahalliy' },
  { en: 'modern', uz: 'zamonaviy' },
  { en: 'ancient', uz: 'qadimiy' },
  { en: 'benefit', uz: 'foyda' },
  { en: 'effect', uz: 'ta’sir' },
  { en: 'cause', uz: 'sabab' },
  { en: 'influence', uz: 'ta’sir qilmoq' },
  { en: 'compare', uz: 'taqqoslamoq' },
  { en: 'opinion', uz: 'fikr' },
  { en: 'agree', uz: 'rozi bo‘lmoq' },
  { en: 'disagree', uz: 'rozi bo‘lmaslik' },
  { en: 'support', uz: 'qo‘llab-quvvatlamoq' },
  { en: 'protect', uz: 'himoya qilmoq' },
  { en: 'prevent', uz: 'oldini olmoq' },
  { en: 'pollution', uz: 'ifloslanish' },
  { en: 'traffic', uz: 'transport harakati' },
  { en: 'transport', uz: 'transport' },
  { en: 'exercise', uz: 'mashq' },
  { en: 'diet', uz: 'parhez' },
  { en: 'energy', uz: 'energiya' },
  { en: 'social media', uz: 'ijtimoiy tarmoqlar' },
  { en: 'education system', uz: 'ta’lim tizimi' },
  { en: 'university', uz: 'universitet' },
  { en: 'scholarship', uz: 'stipendiya' },
  { en: 'competition', uz: 'raqobat' },
  { en: 'industry', uz: 'sanoat' },
  { en: 'business', uz: 'biznes' },
  { en: 'customer', uz: 'mijoz' },
  { en: 'service', uz: 'xizmat' },
  { en: 'product', uz: 'mahsulot' },
  { en: 'advertise', uz: 'reklama qilmoq' },
  { en: 'media', uz: 'ommaviy axborot vositalari' },
  { en: 'article', uz: 'maqola' },
  { en: 'report', uz: 'hisobot' },
  { en: 'discussion', uz: 'muhokama' },
  { en: 'improve skills', uz: 'ko‘nikmalarni oshirmoq' },
  { en: 'make progress', uz: 'rivojlanmoq' },
  { en: 'take responsibility', uz: 'mas’uliyatni olmoq' },
  { en: 'make a decision', uz: 'qaror qabul qilmoq' },
  { en: 'solve a problem', uz: 'muammoni hal qilmoq' },
  { en: 'pay attention', uz: 'e’tibor bermoq' },
  { en: 'spend time', uz: 'vaqt sarflamoq' },
  { en: 'take part', uz: 'qatnashmoq' },
  { en: 'in my opinion', uz: 'mening fikrimcha' },
  { en: 'for example', uz: 'masalan' },
  { en: 'as a result', uz: 'natijada' },
  { en: 'on the other hand', uz: 'boshqa tomondan' },
  { en: 'in conclusion', uz: 'xulosa qilib' },
  { en: 'according to', uz: 'ga ko‘ra' },
  { en: 'such as', uz: 'kabi' },
  { en: 'however', uz: 'ammo' },
  { en: 'therefore', uz: 'shuning uchun' },
  { en: 'although', uz: 'garchi' },
  { en: 'especially', uz: 'ayniqsa' },
  { en: 'probably', uz: 'ehtimol' },
  { en: 'nearly', uz: 'deyarli' },
  { en: 'currently', uz: 'hozirda' },
  { en: 'recently', uz: 'yaqinda' },
  { en: 'future', uz: 'kelajak' },
  { en: 'challenge', uz: 'qiyinchilik' },
  { en: 'successful', uz: 'muvaffaqiyatli' },
  { en: 'confident', uz: 'ishonchli' },
  { en: 'independent', uz: 'mustaqil' },
  { en: 'creative', uz: 'ijodkor' },
  { en: 'responsible', uz: 'mas’uliyatli' },
  { en: 'significant', uz: 'muhim / sezilarli' },
  { en: 'essential', uz: 'zarur' },
  { en: 'accurate', uz: 'aniq' },
  { en: 'efficient', uz: 'samarali' },
  { en: 'flexible', uz: 'moslashuvchan' },
  { en: 'reliable', uz: 'ishonchli' },
  { en: 'convenient', uz: 'qulay' },
  { en: 'complex', uz: 'murakkab' },
  { en: 'harmful', uz: 'zararli' },
  { en: 'beneficial', uz: 'foydali' },
  { en: 'advanced', uz: 'rivojlangan' },
  { en: 'ordinary', uz: 'oddiy' },
  { en: 'valuable', uz: 'qimmatli' },
  { en: 'crowded', uz: 'gavjum' },
  { en: 'peaceful', uz: 'tinch' },
  { en: 'wealthy', uz: 'boy' },
  { en: 'poverty', uz: 'qashshoqlik' },
  { en: 'urban', uz: 'shahar' },
  { en: 'rural', uz: 'qishloq' },
  { en: 'consume', uz: 'iste’mol qilmoq' },
  { en: 'produce_verb', uz: 'ishlab chiqarmoq' },
  { en: 'encourage', uz: 'rag‘batlantirmoq' },
  { en: 'discourage', uz: 'qaytarmoq' },
  { en: 'motivate', uz: 'motivatsiya bermoq' },
  { en: 'participate', uz: 'qatnashmoq' },
  { en: 'communicate_verb', uz: 'muloqot qilmoq' },
  { en: 'concentrate', uz: 'diqqatni jamlamoq' },
  { en: 'organize', uz: 'tashkil qilmoq' },
  { en: 'manage_verb', uz: 'boshqarmoq' },
  { en: 'maintain', uz: 'saqlamoq' },
  { en: 'replace', uz: 'almashtirmoq' },
  { en: 'require', uz: 'talab qilmoq' },
  { en: 'provide_verb', uz: 'ta’minlamoq' },
  { en: 'determine', uz: 'aniqlamoq' },
  { en: 'affect_verb', uz: 'ta’sir qilmoq' },
  { en: 'reduce', uz: 'kamaytirmoq' },
  { en: 'expand', uz: 'kengaytirmoq' },
  { en: 'depend on', uz: 'bog‘liq bo‘lmoq' },
  { en: 'deal with', uz: 'hal qilmoq' },
  { en: 'contribute', uz: 'hissa qo‘shmoq' },
  { en: 'prefer', uz: 'afzal ko‘rmoq' },
  { en: 'avoid', uz: 'qochmoq' },
  { en: 'achieve a goal', uz: 'maqsadga erishmoq' },
  { en: 'make an effort', uz: 'harakat qilmoq' },
  { en: 'gain experience', uz: 'tajriba orttirmoq' },
  { en: 'solve issues', uz: 'muammolarni hal qilmoq' },
  { en: 'critical thinking', uz: 'tanqidiy fikrlash' },
  { en: 'communication skills', uz: 'muloqot ko‘nikmalari' },
  { en: 'higher education', uz: 'oliy ta’lim' },
  { en: 'public transport', uz: 'jamoat transporti' },
  { en: 'climate change', uz: 'iqlim o‘zgarishi' },
  { en: 'natural resources', uz: 'tabiiy resurslar' },
  { en: 'renewable energy', uz: 'qayta tiklanuvchi energiya' },
  { en: 'technological development', uz: 'texnologik rivojlanish' },
  { en: 'financial support', uz: 'moliyaviy yordam' },
  { en: 'mental health', uz: 'ruhiy salomatlik' },
  { en: 'physical activity', uz: 'jismoniy faollik' },
  { en: 'online learning', uz: 'onlayn ta’lim' },
  { en: 'distance education', uz: 'masofaviy ta’lim' },
  { en: 'artificial intelligence', uz: 'sun’iy intellekt' },
  { en: 'communication technology', uz: 'aloqa texnologiyasi' },
  { en: 'environmental protection', uz: 'atrof-muhitni muhofaza qilish' },
  { en: 'Furthermore', uz: 'bundan tashqari' },
  { en: 'Moreover', uz: 'bundan tashqari' },
  { en: 'In addition', uz: 'qo‘shimcha ravishda' },
  { en: 'Nevertheless', uz: 'shunga qaramay' },
  { en: 'Consequently', uz: 'natijada' },
  { en: 'For instance', uz: 'masalan' },
  { en: 'In contrast', uz: 'akcincha' },
  { en: 'Whereas', uz: 'holbuki' },
  { en: 'Therefore_linking', uz: 'shuning uchun' },
  { en: 'Overall', uz: 'umuman olganda' },
  { en: 'paradigm', uz: 'yondashuv modeli' },
  { en: 'phenomenon', uz: 'hodisa' },
  { en: 'unprecedented', uz: 'misli ko‘rilmagan' },
  { en: 'substantial', uz: 'katta / sezilarli' },
  { en: 'predominantly', uz: 'asosan' },
  { en: 'coherent', uz: 'izchil' },
  { en: 'diverse', uz: 'xilma-xil' },
  { en: 'integral', uz: 'ajralmas' },
  { en: 'crucial_band9', uz: 'juda muhim' },
  { en: 'detrimental', uz: 'zararli' },
  { en: 'facilitate', uz: 'yengillashtirmoq' },
  { en: 'demonstrate', uz: 'namoyish qilmoq' },
  { en: 'illustrate', uz: 'tasvirlamoq' },
  { en: 'establish', uz: 'o‘rnatmoq' },
  { en: 'implement_verb', uz: 'amalga oshirmoq' },
  { en: 'eliminate', uz: 'yo‘q qilmoq' },
  { en: 'enhance', uz: 'kuchaytirmoq' },
  { en: 'generate_verb', uz: 'hosil qilmoq' },
  { en: 'pursue', uz: 'davom ettirmoq' },
  { en: 'address', uz: 'muammoni hal qilmoq' },
  { en: 'sustainable', uz: 'barqaror' },
  { en: 'controversial', uz: 'bahsli' },
  { en: 'sophisticated', uz: 'murakkab / ilg‘or' },
  { en: 'inevitable', uz: 'muqarrar' },
  { en: 'feasible', uz: 'amalga oshirsa bo‘ladigan' },
  { en: 'prominent', uz: 'mashhur' },
  { en: 'remarkable', uz: 'ajoyib' },
  { en: 'excessive', uz: 'ortiqcha' },
  { en: 'minimal', uz: 'juda kam' },
  { en: 'rigorous', uz: 'qat’iy' },
  { en: 'nonetheless', uz: 'shunga qaramay' },
  { en: 'consequently_link', uz: 'natijada' },
  { en: 'thereby', uz: 'shu orqali' },
  { en: 'whereas_link', uz: 'holbuki' },
  { en: 'hence', uz: 'shuning uchun' },
  { en: 'in light of', uz: 'hisobga olib' },
  { en: 'as a result of', uz: 'natijasida' },
  { en: 'to a large extent', uz: 'katta darajada' },
  { en: 'from this perspective', uz: 'shu nuqtai nazardan' },
  { en: 'on the contrary', uz: 'aksincha' },
  { en: 'It is widely acknowledged that...', uz: 'Keng tan olinganki...' },
  { en: 'There is a growing body of evidence that...', uz: 'Ko‘plab dalillar shuni ko‘rsatadiki...' },
  { en: 'This can be attributed to the fact that...', uz: 'Bunga sabab shuki...' },
  { en: 'It is imperative that...', uz: 'Juda muhimki...' },
  { en: 'This trend is likely to persist.', uz: 'Bu tendensiya davom etishi mumkin.' },
  { en: 'A compelling argument is that...', uz: 'Kuchli dalil shuki...' },
  { en: 'river', uz: 'daryo' },
  { en: 'mountain', uz: 'tog‘' },
  { en: 'tree_nature', uz: 'daraxt' },
  { en: 'flower', uz: 'gul' },
  { en: 'animal', uz: 'hayvon' },
  { en: 'dog', uz: 'it' },
  { en: 'cat', uz: 'mushuk' },
  { en: 'bird', uz: 'qush' },
  { en: 'fish', uz: 'baliq' },
  { en: 'horse', uz: 'ot' },
  { en: 'cow', uz: 'sigir' },
  { en: 'chicken', uz: 'tovuq' },
  { en: 'egg', uz: 'tuxum' },
  { en: 'language', uz: 'til' },
  { en: 'English_lang', uz: 'ingliz tili' },
  { en: 'Uzbek_lang', uz: 'o‘zbek tili' },
  { en: 'Minecraft', uz: 'Minecraft (O\'yin)' },
  { en: 'Fortnite', uz: 'Fortnite (O\'yin)' },
  { en: 'PUBG: Battlegrounds', uz: 'PUBG (O\'yin)' },
  { en: 'Call of Duty: Warzone', uz: 'CoD Warzone (O\'yin)' },
  { en: 'Counter-Strike 2', uz: 'CS 2 (O\'yin)' },
  { en: 'Valorant', uz: 'Valorant (O\'yin)' },
  { en: 'League of Legends', uz: 'LoL (O\'yin)' },
  { en: 'Dota 2', uz: 'Dota 2 (O\'yin)' },
  { en: 'Roblox', uz: 'Roblox (O\'yin)' },
  { en: 'GTA V', uz: 'GTA V (O\'yin)' },
  { en: 'Red Dead Redemption 2', uz: 'RDR 2 (O\'yin)' },
  { en: 'The Witcher 3: Wild Hunt', uz: 'The Witcher 3 (O\'yin)' },
  { en: 'Elden Ring', uz: 'Elden Ring (O\'yin)' },
  { en: 'Cyberpunk 2077', uz: 'Cyberpunk 2077 (O\'yin)' },
  { en: 'Assassin’s Creed Valhalla', uz: 'AC Valhalla (O\'yin)' },
  { en: 'Assassin’s Creed Odyssey', uz: 'AC Odyssey (O\'yin)' },
  { en: 'Far Cry 6', uz: 'Far Cry 6 (O\'yin)' },
  { en: 'Far Cry 5', uz: 'Far Cry 5 (O\'yin)' },
  { en: 'Watch Dogs 2', uz: 'Watch Dogs 2 (O\'yin)' },
  { en: 'FIFA 23', uz: 'FIFA 23 (O\'yin)' },
  { en: 'EA Sports FC 24', uz: 'EA FC 24 (O\'yin)' },
  { en: 'NBA 2K24', uz: 'NBA 2K24 (O\'yin)' },
  { en: 'eFootball', uz: 'eFootball (O\'yin)' },
  { en: 'Rocket League', uz: 'Rocket League (O\'yin)' },
  { en: 'Among Us', uz: 'Among Us (O\'yin)' },
  { en: 'Fall Guys', uz: 'Fall Guys (O\'yin)' },
  { en: 'Brawl Stars', uz: 'Brawl Stars (O\'yin)' },
  { en: 'Clash of Clans', uz: 'Clash of Clans (O\'yin)' },
  { en: 'Clash Royale', uz: 'Clash Royale (O\'yin)' },
  { en: 'Candy Crush Saga', uz: 'Candy Crush (O\'yin)' },
  { en: 'Subway Surfers', uz: 'Subway Surfers (O\'yin)' },
  { en: 'Temple Run 2', uz: 'Temple Run 2 (O\'yin)' },
  { en: 'Fruit Ninja', uz: 'Fruit Ninja (O\'yin)' },
  { en: 'Angry Birds', uz: 'Angry Birds (O\'yin)' },
  { en: 'The Sims 4', uz: 'The Sims 4 (O\'yin)' },
  { en: 'SimCity', uz: 'SimCity (O\'yin)' },
  { en: 'Cities: Skylines', uz: 'Cities Skylines (O\'yin)' },
  { en: 'Age of Empires IV', uz: 'Age of Empires IV (O\'yin)' },
  { en: 'Civilization VI', uz: 'Civilization VI (O\'yin)' },
  { en: 'Horizon Zero Dawn', uz: 'Horizon Zero Dawn (O\'yin)' },
  { en: 'Horizon Forbidden West', uz: 'Horizon Forbidden West (O\'yin)' },
  { en: 'God of War', uz: 'God of War (O\'yin)' },
  { en: 'God of War Ragnarök', uz: 'GoW Ragnarök (O\'yin)' },
  { en: 'Spider-Man (PS4)', uz: 'Spider-Man (O\'yin)' },
  { en: 'Spider-Man 2', uz: 'Spider-Man 2 (O\'yin)' },
  { en: 'Hogwarts Legacy', uz: 'Hogwarts Legacy (O\'yin)' },
  { en: 'Starfield', uz: 'Starfield (O\'yin)' },
  { en: 'No Man’s Sky', uz: 'No Man’s Sky (O\'yin)' },
  { en: 'Dead by Daylight', uz: 'Dead by Daylight (O\'yin)' },
  { en: 'Phasmophobia', uz: 'Phasmophobia (O\'yin)' },
  { en: 'Resident Evil 4', uz: 'Resident Evil 4 (O\'yin)' },
  { en: 'Resident Evil Village', uz: 'Resident Evil Village (O\'yin)' },
  { en: 'Outlast', uz: 'Outlast (O\'yin)' },
  { en: 'The Last of Us Part I', uz: 'TLoU Part I (O\'yin)' },
  { en: 'The Last of Us Part II', uz: 'TLoU Part II (O\'yin)' },
  { en: 'Uncharted 4', uz: 'Uncharted 4 (O\'yin)' },
  { en: 'Tomb Raider', uz: 'Tomb Raider (O\'yin)' },
  { en: 'Rise of the Tomb Raider', uz: 'Rise of Tomb Raider (O\'yin)' },
  { en: 'Shadow of the Tomb Raider', uz: 'Shadow of Tomb Raider (O\'yin)' },
  { en: 'Minecraft Dungeons', uz: 'Minecraft Dungeons (O\'yin)' },
  { en: 'Diablo III', uz: 'Diablo III (O\'yin)' },
  { en: 'Diablo IV', uz: 'Diablo IV (O\'yin)' },
  { en: 'Path of Exile', uz: 'Path of Exile (O\'yin)' },
  { en: 'Terraria', uz: 'Terraria (O\'yin)' },
  { en: 'Stardew Valley', uz: 'Stardew Valley (O\'yin)' },
  { en: 'Fallout 4', uz: 'Fallout 4 (O\'yin)' },
  { en: 'Fallout 76', uz: 'Fallout 76 (O\'yin)' },
  { en: 'Skyrim', uz: 'Skyrim (O\'yin)' },
  { en: 'The Elder Scrolls Online', uz: 'TES Online (O\'yin)' },
  { en: 'World of Warcraft', uz: 'WoW (O\'yin)' },
  { en: 'Final Fantasy XIV', uz: 'FF XIV (O\'yin)' },
  { en: 'Genshin Impact', uz: 'Genshin Impact (O\'yin)' },
  { en: 'Honkai: Star Rail', uz: 'Honkai Star Rail (O\'yin)' },
  { en: 'Tower of Fantasy', uz: 'Tower of Fantasy (O\'yin)' },
  { en: 'Overwatch 2', uz: 'Overwatch 2 (O\'yin)' },
  { en: 'Team Fortress 2', uz: 'Team Fortress 2 (O\'yin)' },
  { en: 'Apex Legends', uz: 'Apex Legends (O\'yin)' },
  { en: 'Rainbow Six Siege', uz: 'R6 Siege (O\'yin)' },
  { en: 'Battlefield 2042', uz: 'Battlefield 2042 (O\'yin)' },
  { en: 'Forza Horizon 5', uz: 'Forza Horizon 5 (O\'yin)' },
  { en: 'Need for Speed Heat', uz: 'NFS Heat (O\'yin)' },
  { en: 'Gran Turismo 7', uz: 'GT 7 (O\'yin)' },
  { en: 'Asphalt 9: Legends', uz: 'Asphalt 9 (O\'yin)' },
  { en: 'Mario Kart 8 Deluxe', uz: 'Mario Kart 8 (O\'yin)' },
  { en: 'Super Mario Odyssey', uz: 'Super Mario Odyssey (O\'yin)' },
  { en: 'Super Mario Bros. Wonder', uz: 'Mario Bros Wonder (O\'yin)' },
  { en: 'Donkey Kong Country', uz: 'Donkey Kong (O\'yin)' },
  { en: 'Sonic Frontiers', uz: 'Sonic Frontiers (O\'yin)' },
  { en: 'Sonic Generations', uz: 'Sonic Generations (O\'yin)' },
  { en: 'Cuphead', uz: 'Cuphead (O\'yin)' },
  { en: 'Hollow Knight', uz: 'Hollow Knight (O\'yin)' },
  { en: 'Dead Cells', uz: 'Dead Cells (O\'yin)' },
  { en: 'Slay the Spire', uz: 'Slay the Spire (O\'yin)' },
  { en: 'Among Trees', uz: 'Among Trees (O\'yin)' },
  { en: 'ARK: Survival Evolved', uz: 'ARK (O\'yin)' },
  { en: 'Rust', uz: 'Rust (O\'yin)' },
  { en: 'DayZ', uz: 'DayZ (O\'yin)' },
  { en: 'Project Zomboid', uz: 'Project Zomboid (O\'yin)' },
  { en: 'The Forest', uz: 'The Forest (O\'yin)' },
  { en: 'be', uz: 'bo‘lmoq' },
  { en: 'take', uz: 'olmoq' },
  { en: 'get', uz: 'olmoq / erishmoq' },
  { en: 'give', uz: 'bermoq' },
  { en: 'tell', uz: 'aytmoq' },
  { en: 'person', uz: 'odam' },
  { en: 'year', uz: 'yil' },
  { en: 'thing', uz: 'narsa' },
  { en: 'world', uz: 'dunyo' },
  { en: 'life', uz: 'hayot' },
  { en: 'hand', uz: 'qo‘l' },
  { en: 'eye', uz: 'ko‘z' },
  { en: 'place', uz: 'joy' },
  { en: 'long', uz: 'uzun' },
  { en: 'short', uz: 'qisqa' },
  { en: 'reason', uz: 'sabab' },
  { en: 'result', uz: 'natija' },
  { en: 'solution', uz: 'yechim' },
  { en: 'information', uz: 'ma’lumot' },
  { en: 'idea', uz: 'g‘oya' },
  { en: 'change', uz: 'o‘zgarish' },
  { en: 'improvement', uz: 'yaxshilanish' },
  { en: 'situation', uz: 'vaziyat' },
  { en: 'and', uz: 'va' },
  { en: 'but', uz: 'lekin' },
  { en: 'because', uz: 'chunki' },
  { en: 'so', uz: 'shuning uchun' },
  { en: 'allow', uz: 'ruxsat bermoq' },
  { en: 'appear', uz: 'paydo bo‘lmoq' },
  { en: 'become', uz: 'bo‘lmoq' },
  { en: 'begin', uz: 'boshlamoq' },
  { en: 'continue', uz: 'davom ettirmoq' },
  { en: 'create', uz: 'yaratmoq' },
  { en: 'decide', uz: 'qaror qilmoq' },
  { en: 'depend', uz: 'bog‘liq bo‘lmoq' },
  { en: 'explain', uz: 'tushuntirmoq' },
  { en: 'lead', uz: 'boshqarmoq' },
  { en: 'lose_verb', uz: 'yo‘qotmoq' },
  { en: 'move_verb', uz: 'ko‘chmoq' },
  { en: 'area', uz: 'hudud' },
  { en: 'company', uz: 'kompaniya' },
  { en: 'course', uz: 'kurs' },
  { en: 'decision', uz: 'qaror' },
  { en: 'health', uz: 'sog‘liq' },
  { en: 'history', uz: 'tarix' },
  { en: 'level', uz: 'daraja' },
  { en: 'moment', uz: 'lahza' },
  { en: 'nature', uz: 'tabiat' },
  { en: 'common', uz: 'odatiy' },
  { en: 'effective', uz: 'samarali' },
  { en: 'famous', uz: 'mashhur' },
  { en: 'natural', uz: 'tabiiy' },
  { en: 'normal', uz: 'normal' },
  { en: 'possible', uz: 'mumkin' },
  { en: 'powerful', uz: 'kuchli' },
  { en: 'popular', uz: 'ommabop' },
  { en: 'similar', uz: 'o‘xshash' },
  { en: 'simple', uz: 'oddiy' },
  { en: 'analysis', uz: 'tahlil' },
  { en: 'approach', uz: 'yondashuv' },
  { en: 'assessment', uz: 'baholash' },
  { en: 'concept', uz: 'tushuncha' },
  { en: 'data', uz: 'ma’lumot' },
  { en: 'evidence', uz: 'dalil' },
  { en: 'factor', uz: 'omil' },
  { en: 'impact', uz: 'ta’sir' },
  { en: 'issue', uz: 'muammo' },
  { en: 'method', uz: 'usul' },
  { en: 'policy', uz: 'siyosat' },
  { en: 'process', uz: 'jarayon' },
  { en: 'structure', uz: 'tuzilma' },
  { en: 'theory', uz: 'nazariya' },
  { en: 'despite', uz: 'ga qaramay' },
  { en: 'furthermore_linking', uz: 'bundan tashqari' },
  { en: 'on the other hand_linking', uz: 'boshqa tomondan' },
  { en: 'also', uz: 'ham' },
  { en: 'whereas', uz: 'holbuki' },
  { en: 'consequently', uz: 'natijada' },
  { en: 'nevertheless', uz: 'shunga qaramay' },
  { en: 'in contrast', uz: 'aksincha' },
  { en: 'moreover_link', uz: 'bundan tashqari' },
  { en: 'in addition_link', uz: 'qo‘shimcha ravishda' },
  { en: 'reason_noun', uz: 'sabab' },
  { en: 'result_noun', uz: 'natija' },
  { en: 'advantage_noun', uz: 'foyda' },
  { en: 'disadvantage_noun', uz: 'zarar' },
  { en: 'opinion_noun', uz: 'fikr' },
  { en: 'development_noun', uz: 'rivojlanish' },
  { en: 'society_noun', uz: 'jamiyat' }
];
